### ISSUE TITLE
move repo to huc-knaw organisation

### ISSUE THREAD

**Issue by rlzijdeman** [lilimelgar/schema-iisg-kg#1]
Hi, at some point we would need to move this repo to https://github.com/knaw-huc . @michielhildebrand what would this entail for you? (there is absolutely no rush, though)

**Comment by michielhildebrand** [comment]
Once you have moved it we should update in Spinque Desk where the schema files are loaded from.

**Comment by lilimelgar** [comment]
Hello @rlzijdeman and @michielhildebrand. I checked how to do this transfer and it's not too complicated. But I will do it after the next release this Friday. I will let Michiel know when it's done for updating Desk.

**Comment by lilimelgar** [comment]
Done. @rlzijdeman and @michielhildebrand: The repository ownership was transferred to the HuC: https://github.com/knaw-huc/schema-iisg-kg and the  documentation is now generated here: https://knaw-huc.github.io/schema-iisg-kg/.
